In [2]:
import numpy as np
import numpy.linalg as l

In [83]:
M = np.array([[1,1,0,1],[2,3,0,1],[0,1,1,1],[1,0,0,1]])
M_1 = l.inv(M)
A = np.array([[1,0,1,0],[-7,3,3,3],[-1,0,2,1],[4,-1,0,-1]])

In [84]:
M

array([[1, 1, 0, 1],
       [2, 3, 0, 1],
       [0, 1, 1, 1],
       [1, 0, 0, 1]])

In [85]:
M_1

array([[-3.,  1.,  0.,  2.],
       [ 1., -0., -0., -1.],
       [-4.,  1.,  1.,  2.],
       [ 3., -1.,  0., -1.]])

In [86]:
A

array([[ 1,  0,  1,  0],
       [-7,  3,  3,  3],
       [-1,  0,  2,  1],
       [ 4, -1,  0, -1]])

In [87]:
M_1@A@M

array([[ 1.00000000e+00,  1.00000000e+00,  8.88178420e-16,
         8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        -2.22044605e-16],
       [-4.44089210e-16,  4.44089210e-16,  1.00000000e+00,
         0.00000000e+00],
       [ 8.88178420e-16,  4.44089210e-16, -4.44089210e-16,
         2.00000000e+00]])