In [43]:
from numpy import array
from scipy.linalg import lu

import numpy as np
import scipy.linalg as l
import numpy.linalg as ll

a = np.array([[1,2,0,5],[6,-5,17,-38],[-3,0,-6,9],[-2,1,-5,10]])
a2 = a@a
a3 = a@a2
a4 = a@a3

In [47]:
a

array([[  1,   2,   0,   5],
       [  6,  -5,  17, -38],
       [ -3,   0,  -6,   9],
       [ -2,   1,  -5,  10]])

In [48]:
a2

array([[  3,  -3,   9, -21],
       [  1,  -1,   3,  -7],
       [ -3,   3,  -9,  21],
       [ -1,   1,  -3,   7]])

In [49]:
a3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [50]:
a3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [53]:
a@(a@(a@np.array([1,0,0,0])))

array([0, 0, 0, 0])